export const FAKE_POPULARS = [
  {
    backdrop_path: "/3XjDhPzj7Myr8yzsTO8UB6E2oAu.jpg",
    first_air_date: "2011-02-28",
    genre_ids: [18, 80],
    id: 31586,
    name: "La Reina del Sur",
    origin_country: ["US"],
    original_language: "es",
    original_name: "La Reina del Sur",
    overview:
      "After years of blood, sweat and tears, a woman of humble origin ends up becoming a drug trafficking legend, with all that that means...",
    popularity: 1849.128,
    poster_path: "/uBTlJDdPpRxYTfUnKw4wbuIGSEK.jpg",
    vote_average: 7.8,
    vote_count: 1425,
  },
];

export const FAKE_RECOMMENDATIONS = [
  {
    adult: false,
    backdrop_path: "/qsTlD6rYb5vXOlBTT9Lj2hBp44X.jpg",
    id: 44953,
    name: "The Lord of the Skies",
    original_language: "es",
    original_name: "El señor de los cielos",
    overview:
      "Set in the 1990s, these are the life and times of Amado Carrillo Fuentes, a man who became the head of the Juárez cartel. Nicknamed “El Señor de los Cielos” (Lord of the Skies) because of the large fleet of airplanes he used to transport drugs, he was also known for washing more than $200 million through Colombia to finance his huge fleet. He is described as the most powerful drug trafficker of his time.",
    poster_path: "/Ag7VUdnrRz5Qpq3Yn3E5OCvFnu0.jpg",
    media_type: "tv",
    genre_ids: [80, 18, 10766],
    popularity: 619.907,
    first_air_date: "2013-04-15",
    vote_average: 7.801,
    vote_count: 2126,
    origin_country: ["MX"],
  },
  {
    adult: false,
    backdrop_path: "/xZUZ9i6vVayjyhR1vRo9Bjku4h.jpg",
    id: 63174,
    name: "Lucifer",
    original_language: "en",
    original_name: "Lucifer",
    overview:
      "Bored and unhappy as the Lord of Hell, Lucifer Morningstar abandoned his throne and retired to Los Angeles, where he has teamed up with LAPD detective Chloe Decker to take down criminals. But the longer he's away from the underworld, the greater the threat that the worst of humanity could escape.",
    poster_path: "/ekZobS8isE6mA53RAiGDG93hBxL.jpg",
    media_type: "tv",
    genre_ids: [80, 10765],
    popularity: 780.811,
    first_air_date: "2016-01-25",
    vote_average: 8.508,
    vote_count: 12790,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/qabMMIpNUUKYFqQxHEWErEEBD8G.jpg",
    id: 11250,
    name: "Hidden Passion",
    original_language: "es",
    original_name: "Pasión de gavilanes",
    overview:
      "The Reyes-Elizondo's idyllic lives are shattered by a murder charge against Eric and León.",
    poster_path: "/91UV7pNcDPhIzJl7EuK36sK5vRG.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 239.574,
    first_air_date: "2003-10-21",
    vote_average: 7.641,
    vote_count: 1895,
    origin_country: ["CO"],
  },
  {
    adult: false,
    backdrop_path: "/gYUgaCLjMB9gDNNod3R0OJp5pDQ.jpg",
    id: 16286,
    name: "Yo soy Betty, la fea",
    original_language: "es",
    original_name: "Yo soy Betty, la fea",
    overview:
      "Yo soy Betty, la fea is a telenovela filmed in Colombia, written by Fernando Gaitán and produced from October 25, 1999 to May 8, 2001 by the Colombian network RCN. More than a dozen versions of the telenovela have been made in other countries. In the United States, both the comedy-drama hit Ugly Betty and Televisa program La Fea Más Bella are based on the Colombian soap opera.\n\nBetty, la Fea re-aired on Spanish-language U.S. network TeleFutura in January 2009. Eight years after the telenovela's original run, the highly anticipated return of the original version of Yo Soy Betty, La Fea delivered impressive ratings for the network, attracting over one million viewers, more than half a million of which were adults aged 18–49. In addition, the premiere episode doubled and in some cases nearly tripled its prior audience among all key demographics.\n\nDue to the success of re-runs aired in the United States, in June 2009, Yo soy Betty, la fea re-aired in México on Canal de las Estrellas.\n\nBetty, la Fea is arguably the most successful telenovela of all time and one of the most popular television shows in the world. It is the first telenovela to have been remade worldwide and has been regarded as bringing the telenovela to new levels of success.",
    poster_path: "/iEBOiXiDGaxVR6w8aKgG5MEusuO.jpg",
    media_type: "tv",
    genre_ids: [10766, 35, 18],
    popularity: 71.671,
    first_air_date: "1999-10-25",
    vote_average: 8.334,
    vote_count: 2984,
    origin_country: ["CO"],
  },
  {
    adult: false,
    backdrop_path: "/pnyT1foDmmXTsho2DfxN2ePI8ix.jpg",
    id: 80240,
    name: "The Queen of Flow",
    original_language: "es",
    original_name: "La Reina del Flow",
    overview:
      "After spending seventeen years in prison unfairly, a talented songwriter seeks revenge on the men who sank her and killed her family.",
    poster_path: "/fuVuDYrs8sxvEolnYr0wCSvtyTi.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 240.518,
    first_air_date: "2018-06-12",
    vote_average: 7.98,
    vote_count: 1367,
    origin_country: ["CO"],
  },
  {
    adult: false,
    backdrop_path: "/iukGFUQQWUdgwTGGDLb1Pw3GoZP.jpg",
    id: 62455,
    name: "Locked Up",
    original_language: "es",
    original_name: "Vis a vis",
    overview:
      "Set up to take the blame for corporate fraud, young Macarena Ferreiro is locked up in a high-security women's prison surrounded by tough, ruthless criminals in this tense, provocative Spanish thriller.",
    poster_path: "/1kH9u5DkoDUuIlhFFWjz9VSlKhC.jpg",
    media_type: "tv",
    genre_ids: [18],
    popularity: 126.281,
    first_air_date: "2015-04-20",
    vote_average: 8,
    vote_count: 2231,
    origin_country: ["ES"],
  },
  {
    adult: false,
    backdrop_path: "/33j33midGw49BBxiqlNZeZ6PZ0O.jpg",
    id: 85271,
    name: "WandaVision",
    original_language: "en",
    original_name: "WandaVision",
    overview:
      "Wanda Maximoff and Vision—two super-powered beings living idealized suburban lives—begin to suspect that everything is not as it seems.",
    poster_path: "/glKDfE6btIRcVB5zrjspRIs4r52.jpg",
    media_type: "tv",
    genre_ids: [10765, 9648, 18],
    popularity: 107.886,
    first_air_date: "2021-01-15",
    vote_average: 8.306,
    vote_count: 10633,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/bZGAX8oMDm3Mo5i0ZPKh9G2OcaO.jpg",
    id: 84958,
    name: "Loki",
    original_language: "en",
    original_name: "Loki",
    overview:
      "After stealing the Tesseract during the events of “Avengers: Endgame,” an alternate version of Loki is brought to the mysterious Time Variance Authority, a bureaucratic organization that exists outside of time and space and monitors the timeline. They give Loki a choice: face being erased from existence due to being a “time variant” or help fix the timeline and stop a greater threat.",
    poster_path: "/kEl2t3OhXc3Zb9FBh1AuYzRTgZp.jpg",
    media_type: "tv",
    genre_ids: [18, 10765],
    popularity: 142.854,
    first_air_date: "2021-06-09",
    vote_average: 8.174,
    vote_count: 9422,
    origin_country: ["US"],
  },
  {
    adult: false,
    backdrop_path: "/r1tMESor8QuPVKP2VxcVEX6t6ad.jpg",
    id: 43348,
    name: "Pablo Escobar: The Drug Lord",
    original_language: "es",
    original_name: "Pablo Escobar: El Patrón del Mal",
    overview:
      "Pablo is a man with a natural ability for business. Early in his life, Pablo is introduced to the business of cocaine and the power it yields. A young life of crime lands Pablo in and out of jail as he builds is criminal empire. Pablo expands his power through politics but it is not long before his conflicts as a Congressman and a drug lord collide. Pablo has his enemies executed, but not before the United States activates its own war on the Medellin cartel.",
    poster_path: "/jZqm7HFuxfH9P0LFjQZ8nzrCUHP.jpg",
    media_type: "tv",
    genre_ids: [80, 18],
    popularity: 309.938,
    first_air_date: "2012-05-28",
    vote_average: 7.579,
    vote_count: 3131,
    origin_country: ["CO"],
  },
  {
    adult: false,
    backdrop_path: "/9CBdzw7CK2m6WpfEfqe73V8i5O0.jpg",
    id: 105214,
    name: "Dark Desire",
    original_language: "es",
    original_name: "Oscuro deseo",
    overview:
      "Married Alma spends a fateful weekend away from home that ignites passion, ends in tragedy and leads her to question the truth about those close to her.",
    poster_path: "/uxFNAo2A6ZRcgNASLk02hJUbybn.jpg",
    media_type: "tv",
    genre_ids: [9648, 18],
    popularity: 107.909,
    first_air_date: "2020-07-15",
    vote_average: 7.309,
    vote_count: 4125,
    origin_country: ["MX"],
  },
];
